### ISSUE TITLE
Getting error while compiling in IntelliJ IDEA

### ISSUE THREAD

**Issue by prdas31** [aviplayer/rust_java_ffi#1]
Hi,

Thanks for sharing this.

I'm getting the following error while trying to build the Rust library: (running n WIndows 10, Intellij IDEA + Rust plugin) -

```
D:/Programs/Rust/.cargo/bin/cargo.exe test --color=always --message-format=json-diagnostic-rendered-ansi --no-run --package rust --lib tests
error: package ID specification `rust` did not match any packages
Process finished with exit code 101
```

Could you please help and advise?
Thanks.

**Comment by aviplayer** [comment]
> Hi,
> 
> Thanks for sharing this.
> 
> I'm getting the following error while trying to build the Rust library: (running n WIndows 10, Intellij IDEA + Rust plugin) -
> 
> ```
> D:/Programs/Rust/.cargo/bin/cargo.exe test --color=always --message-format=json-diagnostic-rendered-ansi --no-run --package rust --lib tests
> error: package ID specification `rust` did not match any packages
> Process finished with exit code 101
> ```
> 
> Could you please help and advise? Thanks.

Hi,
You can either build it manually: 
```
cd rust
cargo build
```
In you case I guess it D:/Programs/Rust/.cargo/bin/cargo.exe build
[or create a new config in Intellij IDEA](https://www.screencast.com/t/UJR7rFG0EtbU)
You just need to create dynamic lib and provide path to it as a param for java.

**Comment by prdas31** [comment]
> > Hi,
> > Thanks for sharing this.
> > I'm getting the following error while trying to build the Rust library: (running n WIndows 10, Intellij IDEA + Rust plugin) -
> > ```
> > D:/Programs/Rust/.cargo/bin/cargo.exe test --color=always --message-format=json-diagnostic-rendered-ansi --no-run --package rust --lib tests
> > error: package ID specification `rust` did not match any packages
> > Process finished with exit code 101
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you please help and advise? Thanks.
> 
> Hi, You can either build it manually:
> 
> ```
> cd rust
> cargo build
> ```
> 
> In you case I guess it D:/Programs/Rust/.cargo/bin/cargo.exe build [or create a new config in Intellij IDEA](https://www.screencast.com/t/UJR7rFG0EtbU) You just need to create dynamic lib and provide path to it as a param for java.

Yes, did the build outside Idea as suggested and it worked. Thanks a lot!
